services:
  postgres:
    image: postgres:16
    container_name: trak-pg
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: trak
      POSTGRES_PASSWORD: trak
      POSTGRES_DB: trak_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
